Add model reload function. Closes #22
bonastreyair/node-red-contrib-teachable-machine pull request #24
Opened 2021-09-21 12:58 UTC by acejacek

2021-09-22 08:58 UTC, bonastreyair requested changes
I like the idea but I see here we could split it into two nodes then:
- an `inference` node that just runs inferences of input images (with threshold configs)
- a separate `configuration` or `model` node, where model load, reload related stuff can be statically and dynamically defined

Let me know what you think about it. (I might accept this PR anyway once I tested it, since it is an improvement over current version!)

Remember that doing this change, multiple models should still be able to be loaded with different nodes so this new `inference` node should be able to select which model configuration node to use.

2021-09-22 08:58 UTC, bonastreyair commented on teachable_machine.html
> +                <dd>Set to any value to reload the model. In the same time, ignore image in payload (if any) and do not perform image classification.</dd>
I would say send a `true` value.
```suggestion
                <dd>Set to true to reload the model. In the same time, ignore image in payload (if any) and do not perform image classification.</dd>         
```

2021-09-22 08:58 UTC, bonastreyair commented on package.json
> +  "version": "1.2.3",
Version 1.3.0 since this adds a new functionality that it is backwards compatible
```suggestion
  "version": "1.3.0",
```

2021-09-22 19:44 UTC, acejacek commented
You have an interesting point with this split: having a separate nodes for config and runtime can solve the conflict I have currently with simultaneous processing of image and model reload (due to async processing). Worth to investigate.

2021-09-24 10:29 UTC, bonastreyair commented
I'm going to merge it to dev for testing development and refinement and then publish to main

2021-09-24 10:29 UTC, bonastreyair approved these changes

2021-09-24 10:30 UTC, merged

2021-09-24 16:28 UTC, bonastreyair commented
Thanks a lot! Check out release `1.3.0` is out already in npm and Node-RED!